### PR TITLE
add test for cli

### LINKED ISSUE #7: Add unit test for cli.ts
Unit tests were omitted for the CLI feature of this app as the function simply wraps the underlying logic; however, it is still important it is tested somehow.

I tried using `exec` from the Node.js `child-process` lib but it was returning/resolving before the file operations were complete. If anyone has ideas how to better test this please share! 

Here is the code I came up with for a unit test using `exec`: https://github.com/fastify/compile-schemas-to-typescript/pull/6/commits/cfa85173f4abbdc115cfeab21fcbce66b6438202#diff-583d616f4b01bf1fa153e71c0cef7de7

### PR DESCRIPTION
**Pull request by lundibundi**
Fixes: https://github.com/fastify/compile-schemas-to-typescript/issues/7

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

/cc @mcollina

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
CI is failing :(

**Comment by lundibundi** [comment]
Not sure what is happening the added test actually passes but the existing one fails, timeouts actually.

**Comment by Ethan-Arrowood** [comment]
Hey! Thank you for your contribution, but this repo should probably get archived at this point; see #8

**Comment by lundibundi** [comment]
Oh, didn't notice that.
That's fine then =).

**Pull request closed without merging**
